### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by TonyFred-code** [Zyron-Tech/dummy-backend#1]
# CORS Error Debugging and Fix for Signup Endpoint

## Issue
While testing the signup functionality from the frontend, I'm encountering a **CORS error**. The specific error message is:

Cross-Origin Resource Sharing (CORS) error: preflightMissingAllowOriginHeader

It seems that the browser is sending a preflight `OPTIONS` request, but the server is not responding with the required CORS headers like `Access-Control-Allow-Origin`.

### 1. CORS Headers
Please ensure that the backend API is configured to handle CORS properly. The server should respond with the following headers:

- `Access-Control-Allow-Origin: *` (or specify the origin)
- `Access-Control-Allow-Methods: POST, OPTIONS`
- `Access-Control-Allow-Headers: Content-Type, Authorization`

### 2. Handle Preflight Requests
The server should handle `OPTIONS` preflight requests by returning a `200 OK` status and the necessary headers. Here's an example of what can be added to the top of the PHP script:

```php
header("Access-Control-Allow-Origin: *");
header("Access-Control-Allow-Methods: POST, OPTIONS");
header("Access-Control-Allow-Headers: Content-Type, Authorization");

if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    http_response_code(200);
    exit();
}

**Comment by Zyron-Tech** [comment]
**Author's Response**

Thank you, @TonyFred-code, for pointing out this issue and providing a detailed analysis!

### Issue Resolution
I have implemented the necessary CORS headers across the backend endpoints to ensure that the server properly handles preflight OPTIONS requests. The following headers are now included in each endpoint:

```php
header("Access-Control-Allow-Origin: *");
header("Access-Control-Allow-Methods: POST, GET, OPTIONS, PUT, DELETE");
header("Access-Control-Allow-Headers: Content-Type, Authorization");

if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    http_response_code(200);
    exit();
}
```
**_If you continue to encounter any issues, please clear your browser cache and retest. Let me know if the error persists, and we can further investigate._**
